### ISSUE TITLE
Pronounce "JSON" like "J-sahn" rather than "Jason"

### ISSUE THREAD

**Issue by liuderchi** [PJCHENder/pronounce-correctly-for-taiwanese-programmer#1]
How creator of JSON pronounce it: https://www.youtube.com/watch?v=zhVdWQWKRqM
Wiki: https://en.wikipedia.org/w/index.php?diff=623369883&oldid=623304232&title=JSON

**Comment by PJCHENder** [comment]
closed this in #[c2cbd66](https://github.com/PJCHENder/pronounce-correctly-for-taiwanese-programmer/commit/c2cbd66eece44a1e003aa2121ac63c61e3e8873e)

**Comment by pjchender** [comment]
closed this in #[c2cbd66](https://github.com/PJCHENder/pronounce-correctly-for-taiwanese-programmer/commit/c2cbd66eece44a1e003aa2121ac63c61e3e8873e)

**Comment by PJCHENder** [comment]
closed this in #[c2cbd66](https://github.com/PJCHENder/pronounce-correctly-for-taiwanese-programmer/commit/c2cbd66eece44a1e003aa2121ac63c61e3e8873e)
