### ISSUE TITLE
[補充資料] 台灣工程師常唸錯的英文單字

### ISSUE THREAD

**Issue by AaronChern** [PJCHENder/pronounce-correctly-for-taiwanese-programmer#2]
補充其他資料 請參考 謝謝 

台灣工程師常唸錯的英文單字
http://blog.privism.org/2012/06/blog-post.html

=====

碼天狗 120期
https://weekly.codetengu.com/issues/120

YouGlish - Use YouTube to improve your English pronunciation

因為公司的 System Architect 是加拿大人，所以平常跟他在開會或閒聊都是全英文進行
，對土台灣人如我多少還是有點不習慣，最近的困擾是關於某些單字的唸法，一般的英文
單字也就算了，畢竟網路上隨便一個字典都有真人發音。但是那些我們平常在用的技術詞
彙（例如 framework 或 library 的名字）就不一定在字典裡找得到了。正好前陣子
 @SammyLinTw 推薦了 YouGlish 這個網站，它可以直接幫你列出 YouTube 上關於某個單
字的發音片段，實用！

大家感受一下：

etcd
Ethereum
Kubernetes
pipenv
regex
tmux
uWSGI

**Comment by pjchender** [comment]
謝謝提供！
