### ISSUE TITLE
Phonetics of "resolve" are wrong

### ISSUE THREAD

**Issue by jaidTw** [PJCHENder/pronounce-correctly-for-taiwanese-programmer#3]
<html><body>

resolve 🔊 | ✅ [rɪ'zɒlvd] | ❌ [rɪ'səʊvd]
-- | -- | --

</body>
</html>
There should not be those "d"s at the end

**Comment by pjchender** [comment]
Thanks. Fixed in the commit [(!8955e)](https://github.com/pjchender/pronounce-correctly-for-taiwanese-programmer/commit/8955e930e11b0dff6eb47143dc79e87e1175fe0f).
