### ISSUE TITLE
Django  發音應該有誤

### ISSUE THREAD

**Issue by D50000** [PJCHENder/pronounce-correctly-for-taiwanese-programmer#4]
Django [🔊](http://dict.youdao.com/dictvoice?audio=Django&type=1)
錄音檔是發音 “但狗”，但是後面音標似乎是對的？

reference: https://www.google.com/search?q=django+pronunciation&oq=django+pronunciation&aqs=chrome.0.69i59j0i512l2j0i8i30l5j0i8i15i30j0i5i30.6418j0j7&sourceid=chrome&ie=UTF-8

**Comment by pjchender** [comment]
Are you willing to submit a PR for that?

**Comment by D50000** [comment]
Sure, i will do it later.
